github.com:
    users:
        AxelXrest:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: AxelXrest
